api:
  base-path: /api

server:
  port: 8080

spring:
  messages:
    basename: classpath:/messages
  datasource:
    url: jdbc:sqlserver://sql-conpal-ws-001.database.windows.net:1433;database=ws-group1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    hibernate:
      ddl-auto: none # switch to none when we use liquibase
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

lc:
  cloudfunction-url: ${SPRING_CLOUDFUNCTION_URL}