api:
  base-path: /api

server:
  port: 8080

spring:
  messages:
    basename: classpath:/messages
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=workshop;encrypt=false
    username: sa
    password: Qo_BKT3nNx
  jpa:
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2016Dialect
    hibernate:
      ddl-auto: none # switch to none when we use liquibase
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml