apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.2.0
    tanka.dev/environment: 04b5696c3c9429905531840e1a1a383a55aab7349390e325
  name: nginx
  namespace: lancrypt
spec:
  controller: k8s.io/ingress-nginx
