apiVersion: v1
data: null
kind: ConfigMap
metadata:
  labels:
    app: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    tanka.dev/environment: 04b5696c3c9429905531840e1a1a383a55aab7349390e325
  name: cert-manager-webhook
  namespace: cert-manager
