apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    tanka.dev/environment: 04b5696c3c9429905531840e1a1a383a55aab7349390e325
  name: ingress-nginx
