apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.2.0
    tanka.dev/environment: 04b5696c3c9429905531840e1a1a383a55aab7349390e325
  name: ingress-nginx-admission
  namespace: ingress-nginx
