apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: v1.8.2
    tanka.dev/environment: 04b5696c3c9429905531840e1a1a383a55aab7349390e325
  name: cert-manager
  namespace: cert-manager
