# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ws-spring-backend-db-credentials-group1
  namespace: default
spec:
  parameters:
    keyvaultName: kv-conpal-ws-001
    objects: |
      array:
        - |
          objectName: db-username-ws-group1
          objectType: secret
        - |
          objectName: db-password-ws-group1
          objectType: secret
    tenantId: f70e8e1c-de5c-4b7b-a962-301a87f3f378
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: e369a67a-35f4-49da-bd85-209178a2ee67  #ApplicationID of the azurekeyvaultsecretsprovider-aks-lancrypt-<STAGE> Enterprise application
  provider: azure
  secretObjects:
    - data:
        - key: username
          objectName: db-username-ws-group1
        - key: password
          objectName: db-password-ws-group1
      secretName: ws-spring-backend-db-credentials-group1
      type: Opaque
